### ISSUE TITLE
Using ${{ secrets.GITHUB_TOKEN }} doesn't work in reusable workflow

### ISSUE THREAD

**Issue by wiebeck** [riege/code-quality#14]
In order to use secrets you need to define them similar to inputs and pass them from the calling workflow.

At least that's what I believe when looking at [this error](https://github.com/riege/code-quality/runs/4709085870?check_suite_focus=true) and [this documentation](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow).

**Comment by HardTy** [comment]
The issue should be solved?
